Repository rapidsai/ucx-py, pull requests merged in 2021-05, with the labels that each got.

#731 ENH Remove 'rapidsai-nightly' conda channel when building main branch
  ci/cpu/build.sh
Labels: enhancement

#733 Update release script [skip-ci]
  ci/release/update-version.sh
Labels: improvement, non-breaking

#693 Raise on endpoint error handling, enable it by default in UCX 1.11
  debug-tests/test_endpoint_error_callback.py
  tests/test_custom_send_recv.py
  tests/test_disconnect.py
  tests/test_info.py
  tests/test_shutdown.py
  ucp/_libs/tests/test_config.py
  ucp/_libs/tests/test_mem.py
  ucp/_libs/tests/test_peer_send_recv.py
  ucp/_libs/tests/test_server_client.py
  ucp/_libs/tests/test_server_client_am.py
  ucp/_libs/transfer_stream.pyx
  ucp/_libs/transfer_tag.pyx
  ucp/_libs/ucx_api_dep.pxd
  ucp/_libs/ucx_endpoint.pyx
  ucp/_libs/ucx_worker.pyx
  ucp/_libs/ucx_worker_cb.pyx
  ucp/core.py
  ucp/exceptions.py
Labels: enhancement, non-breaking

#737 Drain tag messages on worker finalizer
  ucp/_libs/ucx_api_dep.pxd
  ucp/_libs/ucx_worker.pyx
Labels: bug
