Repository rapidsai/ucx-py, pull requests merged in 2024-02, with the labels that each got.

#1023 Exclude tests from builds
  pyproject.toml
Labels: bug, non-breaking

#1015 Support CUDA 12.2
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  dependencies.yaml
Labels: enhancement, non-breaking

#1026 target branch-24.04 for GitHub Actions workflows
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: non-breaking, improvement

#1022 Update ops-bot.yaml
  .github/ops-bot.yaml
Labels: non-breaking, improvement

#1025 Add environment-agnostic scripts for running pytests
  ci/run_benchmark_pytests.sh
  ci/run_pytests.sh
  ci/test_python.sh
Labels: non-breaking, improvement

#1027 Add support for Python 3.11
  dependencies.yaml
  docs/source/install.rst
Labels: non-breaking, improvement

#1028 Requre NumPy 1.23+
  dependencies.yaml
  pyproject.toml
Labels: non-breaking, improvement
