Repository rapidsai/ucx-py, pull requests merged in 2025-07, with the labels that each got.

#1150 add docs on CI workflow inputs
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: non-breaking, improvement

#1151 Add deprecation warning
  README.md
Labels: improvement, breaking

#1153 Remove CUDA 11 from install docs
  docs/source/install.rst
Labels: non-breaking, improvement

#1156 chore: bump to 0.46
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  RAPIDS_VERSION
  VERSION
  dependencies.yaml
  pyproject.toml
Labels: non-breaking, improvement

#1144 Adding GH_TOKEN pass-through to summarize job
  .github/workflows/pr.yaml
Labels: bug, non-breaking
